runtime: python38

entrypoint: gunicorn -w 4 app:app

instance_class: F2

env_variables:
  FLASK_ENV: "production"
  SECRET_KEY: "your_secret_key"

handlers:
- url: /templates
  static_dir: templates/

- url: /.*
  script: auto
